variables:
  AZCOPY_GOLANG_VERSION: '1.23.1'

# Do not trigger this pipeline automatically
trigger: none
pr: none

# The `resources` specify the location and version of the 1ES PT.
resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: azcopy-pool  # Name of your hosted pool
        image: windows2022-1espt
        os: windows  # OS of the image. Allowed values: windows, linux, macOS

    stages:
    - stage: BuildArtifacts
      jobs:
      - job: BuildLinux
        pool:
          name: azcopy-pool
          image: ubuntu22-1espt
          os: linux
        # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
        # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)/archives
            artifactName: 'azCopy-linux-temp'

        variables:
          - name: root_dir
            value: '$(System.DefaultWorkingDirectory)'
          - name: archives
            value: '$(System.DefaultWorkingDirectory)/archives'
        # Define the steps that the pipeline will run.
        # In most cases, copy and paste the steps from the original pipeline.
        steps:
        - task: GoTool@0
          env:
            GO111MODULE: 'on'
          inputs:
            version: $(AZCOPY_GOLANG_VERSION)

        - script: |
            go vet 
          displayName: 'Go Vet'

        - script: |
            set -ex
            sudo apt-get clean
            sudo apt-get update --fix-missing
            sudo apt-get install pkg-config libsecret-1-dev -y
            sudo apt-get install ruby ruby-dev rubygems libglib2.0-dev build-essential rpm -y
            sudo gem install dotenv -v 2.8.1
            sudo gem install fpm -V
          displayName: "Install Dependencies"

        - script: |
            set -ex
            GOARCH=amd64 GOOS=linux go build -tags "netgo" -o "$(root_dir)/azcopy_linux_amd64"
            GOARCH=amd64 GOOS=linux go build -tags "netgo,se_integration" -o "$(root_dir)/azcopy_linux_se_amd64"
          displayName: 'Build AzCopy for Linux'

        - task: Bash@3
          displayName: 'Extract AzCopy Version'
          inputs:
            targetType: 'inline'
            script: |
              azcopy_version=$($(root_dir)/azcopy_linux_amd64 --version | awk '{print $3}' | head -n 1)
              echo "##vso[task.setvariable variable=azcopy_version]$azcopy_version"

        - script: |
            set -e
            linux_amd64_dir="$(root_dir)/azcopy_linux_amd64_$(azcopy_version)"
            echo "##vso[task.setvariable variable=linux_amd64_dir]$linux_amd64_dir"
            linux_se_amd64_dir="$(root_dir)/azcopy_linux_se_amd64_$(azcopy_version)"
            echo "##vso[task.setvariable variable=linux_se_amd64_dir]$linux_se_amd64_dir"
            mkdir -pv $linux_amd64_dir
            mkdir -pv $linux_se_amd64_dir
            mkdir -pv $(archives)
          displayName: 'Create Required Directories for Packaging'
        
        - script: |
            set -e
            mkdir -pv pkgDir/usr/bin
            mv -v "$(root_dir)/azcopy_linux_amd64"  "$(linux_amd64_dir)/azcopy"
            mv -v "$(root_dir)/azcopy_linux_se_amd64"  "$(linux_se_amd64_dir)/azcopy"
            cp -v "$(linux_amd64_dir)/azcopy" pkgDir/usr/bin/
            cp -v NOTICE.txt "$(linux_amd64_dir)"
            cp -v NOTICE.txt "$(linux_se_amd64_dir)"
            cp -v NOTICE.txt pkgDir/usr/bin/
          displayName: 'Copy Files for Packaging'

        # using fpm tool for packaging of our binary & performing post-install operations
        # for additional information about fpm refer https://fpm.readthedocs.io/en/v1.13.1/
        - script: |
            fpm -s dir -t deb -n azcopy -C pkgDir/ \
            -v $(azcopy_version) \
            --maintainer "Azcopy v-Team <azcopyvteam@microsoft.com>" \
            --url "https://github.com/Azure/azure-storage-azcopy" \
            --description "A command-line utility that is used to copy data to and from containers and file shares in Azure Storage accounts" 
            mv ./azcopy*.deb ./azcopy-$(azcopy_version).amd64.deb
            cp ./azcopy*.deb $(archives)
          displayName: 'Make AMD64 deb Package'

        - script: |
            fpm -s dir -t rpm -n azcopy --rpm-digest sha256 -C pkgDir/ \
            -v $(azcopy_version) \
            --maintainer "Azcopy v-Team <azcopyvteam@microsoft.com>" \
            --url "https://github.com/Azure/azure-storage-azcopy" \
            --description "A command-line utility that is used to copy data to and from containers and file shares in Azure Storage accounts" 
            mv ./azcopy*.rpm ./azcopy-$(azcopy_version).amd64.rpm
            cp ./azcopy*.rpm $(archives)
          displayName: 'Make AMD64 rpm Package'

        - task: ArchiveFiles@2
          displayName: 'Archive Standard Linux Build'
          inputs:
            rootFolderOrFile: '$(linux_amd64_dir)'
            archiveType: tar
            archiveFile: '$(archives)/azcopy_linux_amd64_$(azcopy_version).tar.gz'

        - task: ArchiveFiles@2
          displayName: 'Archive Partner(SE) Linux Build'
          inputs:
            rootFolderOrFile: '$(linux_se_amd64_dir)'
            archiveType: tar
            archiveFile: '$(archives)/azcopy_linux_se_amd64_$(azcopy_version).tar.gz'

      - job: BuildLinuxARM
        pool:
          name: azcopy-arm-pool
          image: mariner2arm-1espt
          os: linux
          hostArchitecture: Arm64
        # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
        # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
        templateContext:
          outputs:
            - output: pipelineArtifact
              targetPath: $(System.DefaultWorkingDirectory)/archives
              artifactName: 'azCopy-linux-temp'

        variables:
          - name: root_dir
            value: '$(System.DefaultWorkingDirectory)'
          - name: archives
            value: '$(System.DefaultWorkingDirectory)/archives'
        # Define the steps that the pipeline will run.
        # In most cases, copy and paste the steps from the original pipeline.
        steps:
          - task: GoTool@0
            env:
              GO111MODULE: 'on'
            inputs:
              version: $(AZCOPY_GOLANG_VERSION)

          - script: |
              go vet
            displayName: 'Go Vet'

          - script: |
              set -ex
              sudo apt-get clean
              sudo apt-get update --fix-missing
              sudo apt-get install pkg-config libsecret-1-dev -y
              sudo apt-get install ruby ruby-dev rubygems libglib2.0-dev build-essential rpm -y
              sudo gem install dotenv -v 2.8.1
              sudo gem install fpm -V
            displayName: "Install Dependencies"

          - script: |
              set -ex
              GOARCH=arm64 GOOS=linux go build -tags "netgo" -o "$(root_dir)/arm64"
              GOARCH=arm64 GOOS=linux go build -tags "netgo,se_integration" -o "$(root_dir)/azcopy_linux_se_arm64"
            displayName: 'Build AzCopy for Linux ARM64'

          - task: Bash@3
            displayName: 'Extract AzCopy Version'
            inputs:
              targetType: 'inline'
              script: |
                azcopy_version=$($(root_dir)/azcopy_linux_amd64 --version | awk '{print $3}' | head -n 1)
                echo "##vso[task.setvariable variable=azcopy_version]$azcopy_version"

      - job: BuildWindows
        pool:
          name: azcopy-pool
          image: windows2022-1espt
          os: windows
        # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
        # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)/binaries
            artifactName: 'azCopy-windows-temp'

        variables:
          - name: binaries
            value: '$(System.DefaultWorkingDirectory)/binaries'
        # Define the steps that the pipeline will run.
        # In most cases, copy and paste the steps from the original pipeline.
        steps:
        - task: GoTool@0
          env:
            GO111MODULE: 'on'
          inputs:
            version: $(AZCOPY_GOLANG_VERSION)

        - script: |
            go vet 
          displayName: 'Go Vet'

        - script: |
            mkdir "$(binaries)"
          displayName: 'Create Required Directories for Packaging'

        - script: |
            go build -o "$(binaries)\azcopy_windows_amd64.exe"
          displayName: 'Build AzCopy for Windows AMD64'
          env:
            GOARCH: amd64
            GOOS: windows
            CGO_ENABLED: 0

        - script: |
            go build -o "$(binaries)\azcopy_windows_386.exe"
          displayName: 'Build AzCopy for Windows i386'
          env:
            GOARCH: "386"
            GOOS: windows
            CGO_ENABLED: 0

        - script: |
            go build -o "$(binaries)\azcopy_windows_v7_arm.exe"
          displayName: 'Build AzCopy for Windows ARM v7'
          env:
            GOARCH: arm
            GOARM: 7
            GOOS: windows
            CGO_ENABLED: 0

        - script: |
            go build -o "$(binaries)\azcopy_windows_arm64.exe"
          displayName: 'Build AzCopy for Windows ARM64'
          env:
            GOARCH: arm64
            GOOS: windows
            CGO_ENABLED: 0

      - job: BuildMacOS
        pool:
          name: Azure Pipelines
          image: macos-latest
          os: macOS
        # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
        # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)/archives
            artifactName: 'azCopy-mac-temp'
        # Define the steps that the pipeline will run.
        # In most cases, copy and paste the steps from the original pipeline.
        variables:
          - group: AZCOPY_TESTS_VAR
          - name: root_dir
            value: '$(System.DefaultWorkingDirectory)'
          - name: archives
            value: $(root_dir)/archives
        steps:
        - task: GoTool@0
          env:
            GO111MODULE: 'on'
          inputs:
            version: $(AZCOPY_GOLANG_VERSION)

        - script: |
            set -ex
            go vet 
            CGO_ENABLED=1 go build -o "$(root_dir)/azcopy_darwin_amd64"
            GOARCH=arm64 CGO_ENABLED=1 go build -o "$(root_dir)/azcopy_darwin_arm64" 
          displayName: 'Build AzCopy for MacOS'

        - task: Bash@3
          displayName: 'Extract AzCopy Version'
          inputs:
            targetType: 'inline'
            script: |
              azcopy_version=$($(root_dir)/azcopy_darwin_amd64 --version | awk '{print $3}')
              echo "##vso[task.setvariable variable=azcopy_version]$azcopy_version"

        - template: setup/trigger_m1_build.yml@self
          
        - script: |
            set -ex
            darwin_amd_dir="$(root_dir)/azcopy_darwin_amd64_$(azcopy_version)"
            echo "##vso[task.setvariable variable=darwin_amd_dir]$darwin_amd_dir"
            darwin_arm_dir="$(root_dir)/azcopy_darwin_arm64_$(azcopy_version)"
            echo "##vso[task.setvariable variable=darwin_arm_dir]$darwin_arm_dir"  
            darwin_arm64_m1_dir="$(root_dir)/azcopy_darwin_m1_arm64_$(azcopy_version)"  
            echo "##vso[task.setvariable variable=darwin_arm64_m1_dir]$darwin_arm64_m1_dir"
            mkdir -p $darwin_amd_dir
            mkdir -p $darwin_arm_dir
            mkdir -p $darwin_arm64_m1_dir
            mkdir -p $(archives)
          displayName: 'Create Required Directories for Packaging'

        - script: |
            set -ex
            cp NOTICE.txt $(darwin_amd_dir)
            cp NOTICE.txt $(darwin_arm_dir)
            cp NOTICE.txt $(darwin_arm64_m1_dir)
            mv $(root_dir)/azcopy_darwin_amd64  $(darwin_amd_dir)/azcopy
            mv $(root_dir)/azcopy_darwin_arm64  $(darwin_arm_dir)/azcopy
            cp $(Build.ArtifactStagingDirectory)/azcopy  $(darwin_arm64_m1_dir)/azcopy
          displayName: 'Copy Files for Packaging'

        - task: ArchiveFiles@2
          displayName: 'Archive MacOS AMD64 Build (must happen before signing/notarization)'
          inputs:
            rootFolderOrFile: '$(darwin_amd_dir)'
            archiveFile: '$(archives)/azcopy_darwin_amd64_$(azcopy_version).zip'

        - task: ArchiveFiles@2
          displayName: 'Archive MacOS ARM64 Build (must happen before signing/notarization)'
          inputs:
            rootFolderOrFile: '$(darwin_arm_dir)'
            archiveFile: '$(archives)/azcopy_darwin_arm64_$(azcopy_version).zip'
        
        - task: ArchiveFiles@2
          displayName: 'Archive MacOS M1_ARM64 Build (must happen before signing/notarization)'
          inputs:
            rootFolderOrFile: '$(darwin_arm64_m1_dir)'
            archiveFile: '$(archives)/azcopy_darwin_m1_arm64_$(azcopy_version).zip'