trigger: none
pr: none

parameters:
  - name: action
    displayName: 'Action'
    type: string
    default: Validate
    values:
      - Validate
      - Deploy
  - name: azureServiceConnection
    displayName: 'Deployment workload-identity service connection'
    type: string
    default: azcopytelemetrydeploymentidentity

stages:
  - template: azurePipelineTemplates/telemetry-infrastructure-stages.yml
    parameters:
      action: ${{ parameters.action }}
      azureServiceConnection: ${{ parameters.azureServiceConnection }}
