// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: grpcctl.proto

package internal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AzCopyControlClient is the client API for AzCopyControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AzCopyControlClient interface {
	InjectToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*EmptyReply, error)
}

type azCopyControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAzCopyControlClient(cc grpc.ClientConnInterface) AzCopyControlClient {
	return &azCopyControlClient{cc}
}

func (c *azCopyControlClient) InjectToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, "/AzCopyControl/InjectToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AzCopyControlServer is the server API for AzCopyControl service.
// All implementations must embed UnimplementedAzCopyControlServer
// for forward compatibility
type AzCopyControlServer interface {
	InjectToken(context.Context, *Token) (*EmptyReply, error)
	mustEmbedUnimplementedAzCopyControlServer()
}

// UnimplementedAzCopyControlServer must be embedded to have forward compatible implementations.
type UnimplementedAzCopyControlServer struct {
}

func (UnimplementedAzCopyControlServer) InjectToken(context.Context, *Token) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectToken not implemented")
}
func (UnimplementedAzCopyControlServer) mustEmbedUnimplementedAzCopyControlServer() {}

// UnsafeAzCopyControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AzCopyControlServer will
// result in compilation errors.
type UnsafeAzCopyControlServer interface {
	mustEmbedUnimplementedAzCopyControlServer()
}

func RegisterAzCopyControlServer(s grpc.ServiceRegistrar, srv AzCopyControlServer) {
	s.RegisterService(&AzCopyControl_ServiceDesc, srv)
}

func _AzCopyControl_InjectToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AzCopyControlServer).InjectToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AzCopyControl/InjectToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AzCopyControlServer).InjectToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// AzCopyControl_ServiceDesc is the grpc.ServiceDesc for AzCopyControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AzCopyControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AzCopyControl",
	HandlerType: (*AzCopyControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InjectToken",
			Handler:    _AzCopyControl_InjectToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcctl.proto",
}
