// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: grpcctl.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Usually "OK"
	Status *string `protobuf:"bytes,1,req,name=Status" json:"Status,omitempty"`
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azcopy_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_azcopy_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_azcopy_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *EmptyReply) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BearerToken *string `protobuf:"bytes,1,req,name=BearerToken" json:"BearerToken,omitempty"`
	UnixExpiry  *int64  `protobuf:"varint,2,req,name=UnixExpiry" json:"UnixExpiry,omitempty"`
	UnixLive    *int64  `protobuf:"varint,3,req,name=UnixLive" json:"UnixLive,omitempty"`
	Wiggle      *int64  `protobuf:"varint,4,req,name=Wiggle" json:"Wiggle,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azcopy_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_azcopy_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_azcopy_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetBearerToken() string {
	if x != nil && x.BearerToken != nil {
		return *x.BearerToken
	}
	return ""
}

func (x *Token) GetUnixExpiry() int64 {
	if x != nil && x.UnixExpiry != nil {
		return *x.UnixExpiry
	}
	return 0
}

func (x *Token) GetUnixLive() int64 {
	if x != nil && x.UnixLive != nil {
		return *x.UnixLive
	}
	return 0
}

func (x *Token) GetWiggle() int64 {
	if x != nil && x.Wiggle != nil {
		return *x.Wiggle
	}
	return 0
}

var File_azcopy_grpc_proto protoreflect.FileDescriptor

var file_azcopy_grpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x7a, 0x63, 0x6f, 0x70, 0x79, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x7d, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x6e, 0x69, 0x78, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0a, 0x55, 0x6e, 0x69, 0x78, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x6e, 0x69, 0x78, 0x4c, 0x69, 0x76, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x08, 0x55, 0x6e, 0x69, 0x78, 0x4c, 0x69, 0x76, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x57, 0x69, 0x67, 0x67, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03,
	0x52, 0x06, 0x57, 0x69, 0x67, 0x67, 0x6c, 0x65, 0x32, 0x35, 0x0a, 0x0d, 0x41, 0x7a, 0x43, 0x6f,
	0x70, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x0b, 0x49, 0x6e, 0x6a,
	0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x06, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x1a, 0x0b, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x7a,
	0x75, 0x72, 0x65, 0x2f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2d, 0x61, 0x7a, 0x63, 0x6f, 0x70, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x63, 0x74, 0x6c,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
}

var (
	file_azcopy_grpc_proto_rawDescOnce sync.Once
	file_azcopy_grpc_proto_rawDescData = file_azcopy_grpc_proto_rawDesc
)

func file_azcopy_grpc_proto_rawDescGZIP() []byte {
	file_azcopy_grpc_proto_rawDescOnce.Do(func() {
		file_azcopy_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_azcopy_grpc_proto_rawDescData)
	})
	return file_azcopy_grpc_proto_rawDescData
}

var file_azcopy_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_azcopy_grpc_proto_goTypes = []interface{}{
	(*EmptyReply)(nil), // 0: EmptyReply
	(*Token)(nil),      // 1: Token
}
var file_azcopy_grpc_proto_depIdxs = []int32{
	1, // 0: AzCopyControl.InjectToken:input_type -> Token
	0, // 1: AzCopyControl.InjectToken:output_type -> EmptyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_azcopy_grpc_proto_init() }
func file_azcopy_grpc_proto_init() {
	if File_azcopy_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_azcopy_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_azcopy_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_azcopy_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_azcopy_grpc_proto_goTypes,
		DependencyIndexes: file_azcopy_grpc_proto_depIdxs,
		MessageInfos:      file_azcopy_grpc_proto_msgTypes,
	}.Build()
	File_azcopy_grpc_proto = out.File
	file_azcopy_grpc_proto_rawDesc = nil
	file_azcopy_grpc_proto_goTypes = nil
	file_azcopy_grpc_proto_depIdxs = nil
}
