package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"net/http"
	"os"
	"runtime"
	"time"

	"github.com/Azure/azure-storage-azcopy/v10/common"
	aztelemetry "github.com/Azure/azure-storage-azcopy/v10/telemetry"
)

const (
	connectionString = "InstrumentationKey=8e8fa50e-9cf1-4d8f-a765-4a85d3bb8a1f;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=63982dde-13f2-4dfe-8684-69831854f4b2"
	jobsPerCommand   = 5
)

func main() {
	dryRun := flag.Bool("dry-run", false, "build and summarize events without sending them")
	payloadOutput := flag.String("write-payloads", "", "write representative production-serialized payloads to a Markdown file without sending them")
	timeout := flag.Duration("timeout", 2*time.Minute, "overall timeout for sending sample events")
	flag.Parse()

	events := buildSampleEvents(time.Now().UTC())
	if *payloadOutput != "" {
		if err := writePayloadSamples(*payloadOutput, events); err != nil {
			log.Fatalf("write sample payloads: %v", err)
		}
		fmt.Printf("wrote representative telemetry payloads to %s; no telemetry sent\n", *payloadOutput)
		return
	}
	if *dryRun {
		printEventSummary(events)
		return
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	reporter := aztelemetry.NewReporter(aztelemetry.Config{
		Backend:          aztelemetry.BackendAppInsights,
		ConnectionString: connectionString,
	})
	if err := reporter.ReportEvents(ctx, events...); err != nil {
		log.Fatalf("send sample telemetry: %v", err)
	}

	fmt.Printf("sent %d sample telemetry events: 1 command, %d copy attempts, and %d sync attempts\n", len(events), jobsPerCommand, jobsPerCommand)
}

type captureHTTPClient struct {
	body []byte
}

func (client *captureHTTPClient) Do(request *http.Request) (*http.Response, error) {
	body, err := io.ReadAll(request.Body)
	if err != nil {
		return nil, err
	}
	client.body = body
	return &http.Response{
		StatusCode: http.StatusOK,
		Body:       io.NopCloser(bytes.NewReader(nil)),
		Header:     make(http.Header),
	}, nil
}

func writePayloadSamples(outputPath string, events []aztelemetry.MetricEvent) error {
	representative := make(map[string]aztelemetry.MetricEvent)
	for _, event := range events {
		key := event.EventName()
		switch typed := event.(type) {
		case aztelemetry.JobStartedEvent:
			key = typed.Dimensions.Command + ".started"
		case aztelemetry.JobFinishedEvent:
			key = typed.Dimensions.Command + ".finished"
		}
		if _, exists := representative[key]; !exists {
			representative[key] = event
		}
	}

	sections := []struct {
		title string
		key   string
	}{
		{title: "Command Invoked", key: "azcopy.command.invoked"},
		{title: "Copy Job Started", key: "copy.started"},
		{title: "Copy Job Finished", key: "copy.finished"},
		{title: "Sync Job Started", key: "sync.started"},
		{title: "Sync Job Finished", key: "sync.finished"},
	}

	var markdown bytes.Buffer
	markdown.WriteString("# AzCopy Sample Telemetry JSON Payloads\n\n")
	markdown.WriteString("These are representative request bodies generated by the production `telemetry.Reporter` direct Application Insights path. Each lifecycle event is sent to `/v2.1/track` as one packed custom-event envelope. Numeric measurements share one `measurements` map instead of repeating dimensions in separate metric rows. The capture uses the sample app's real event objects and serializer but an in-memory HTTP client, so generating this file does not send telemetry.\n\n")
	markdown.WriteString("The five copy and five sync attempts have the same payload shape; values such as IDs, timestamps, counters, and terminal status vary per attempt. The examples below use the first completed attempt of each command.\n\n")

	for _, section := range sections {
		event, exists := representative[section.key]
		if !exists {
			return fmt.Errorf("representative event %q not found", section.key)
		}
		client := &captureHTTPClient{}
		reporter := aztelemetry.NewReporter(aztelemetry.Config{
			Backend:          aztelemetry.BackendAppInsights,
			ConnectionString: connectionString,
			HTTPClient:       client,
		})
		if err := reporter.ReportEvent(context.Background(), event); err != nil {
			return err
		}

		var formatted bytes.Buffer
		if err := json.Indent(&formatted, client.body, "", "  "); err != nil {
			return fmt.Errorf("format %s payload: %w", section.key, err)
		}
		fmt.Fprintf(&markdown, "## %s\n\n```json\n%s\n```\n\n", section.title, formatted.String())
	}

	return os.WriteFile(outputPath, markdown.Bytes(), 0600)
}

func buildSampleEvents(now time.Time) []aztelemetry.MetricEvent {
	runToken := fmt.Sprintf("%d", now.UnixNano())
	random := rand.New(rand.NewSource(now.UnixNano()))
	resource := sampleResource()
	events := make([]aztelemetry.MetricEvent, 0, 1+jobsPerCommand*4)
	events = append(events, aztelemetry.CommandInvokedEvent{
		Resource:     resource,
		Command:      "jobs.list",
		JobID:        "telemetry-sample-command-job-" + runToken,
		InvocationID: "telemetry-sample-command-" + runToken,
		Timestamp:    now.Add(-25 * time.Minute),
		InvokedCount: 1,
	})

	for commandIndex, command := range []string{"copy", "sync"} {
		for jobIndex := 0; jobIndex < jobsPerCommand; jobIndex++ {
			sequence := commandIndex*jobsPerCommand + jobIndex
			start := now.Add(-time.Duration(24-sequence*2+random.Intn(3)) * time.Minute)
			duration := time.Duration(randomInt64(random, 45, 600)) * time.Second
			runID := fmt.Sprintf("telemetry-sample-%s-%s-%d", command, runToken, jobIndex+1)
			invocationID := fmt.Sprintf("telemetry-sample-invocation-%s-%s-%d", command, runToken, jobIndex+1)
			dimensions := sampleDimensions(command, jobIndex)

			events = append(events, aztelemetry.JobStartedEvent{
				Resource:     resource,
				Dimensions:   dimensions,
				JobID:        runID,
				InvocationID: invocationID,
				Timestamp:    start,
				StartedCount: 1,
			})
			events = append(events, sampleFinishedEvent(random, resource, dimensions, runID, invocationID, start, duration, jobIndex))
		}
	}

	return events
}

func sampleResource() aztelemetry.ResourceAttributes {
	return aztelemetry.ResourceAttributes{
		AzCopyVersion:      common.AzcopyVersion,
		SchemaVersion:      "3",
		SamplingRate:       1,
		SamplerVersion:     "telemetry-sample-v1",
		OSType:             runtime.GOOS,
		OSVersion:          "sample-data",
		HostArch:           runtime.GOARCH,
		HostNumCPU:         runtime.NumCPU(),
		HostCPUModel:       "sample-data",
		HostMemoryTotalGB:  16,
		HostNICSpeedMbps:   10000,
		HostNICSpeedBucket: "10-<40gbps",
		AzureVMDetected:    false,
		InstallationID:     "telemetry-sample",
		InvocationContext:  "ci",
	}
}

func sampleDimensions(command string, jobIndex int) aztelemetry.JobDimensions {
	variants := []aztelemetry.JobDimensions{
		{
			FromTo: "LocalBlob", SourceType: "Local", DestType: "Blob",
			SourceProtocol: "local", SourceMountType: "local-disk", SourceScope: "local-directory",
			DestProtocol: "https", DestStorageAccount: "azcopytelemetrysample", DestScope: "container", DestEndpointKind: "public",
			DestCloudType: "public", SourceAuthMechanism: "NotApplicable", DestAuthMechanism: "SAS",
		},
		{
			FromTo: "BlobLocal", SourceType: "Blob", DestType: "Local",
			SourceProtocol: "https", SourceMountType: "cloud-azure", SourceStorageAccount: "azcopytelemetrysource", SourceScope: "service",
			DestProtocol: "local", DestScope: "local-directory",
			SourceCloudType: "public", SourceAuthMechanism: "OAuthToken", DestAuthMechanism: "NotApplicable",
		},
		{
			FromTo: "BlobBlob", SourceType: "Blob", DestType: "Blob",
			SourceProtocol: "https", SourceMountType: "cloud-azure", SourceStorageAccount: "azcopytelemetrysource", SourceScope: "container",
			DestProtocol: "https", DestStorageAccount: "azcopytelemetryprivate", DestScope: "container", DestEndpointKind: "private-endpoint",
			SourceCloudType: "public", DestCloudType: "public", SourceAuthMechanism: "OAuthToken", DestAuthMechanism: "OAuthToken",
		},
		{
			FromTo: "S3Blob", SourceType: "S3", DestType: "Blob",
			SourceProtocol: "s3", SourceMountType: "cloud-s3", SourceScope: "bucket",
			DestProtocol: "https", DestStorageAccount: "azcopytelemetrysample", DestScope: "container", DestEndpointKind: "public",
			DestCloudType: "public", SourceAuthMechanism: "AccessKey", DestAuthMechanism: "OAuthToken",
		},
		{
			FromTo: "GCPBlob", SourceType: "GCP", DestType: "Blob",
			SourceProtocol: "gcs", SourceMountType: "cloud-gcs", SourceScope: "bucket",
			DestProtocol: "https", DestStorageAccount: "azcopytelemetrygov", DestScope: "container", DestEndpointKind: "public",
			DestCloudType: "gov", SourceAuthMechanism: "OAuthToken", DestAuthMechanism: "SAS",
		},
	}

	dimensions := variants[jobIndex%len(variants)]
	dimensions.Command = command
	dimensions.Options = aztelemetry.OptionAttributes{
		FlagsSet:   []string{"recursive", "put-md5"},
		EnvVarsSet: []string{"AZCOPY_CONCURRENCY_VALUE"},
		Values: map[string]string{
			"OptRecursive":   "true",
			"OptPutMD5":      "true",
			"OptConcurrency": fmt.Sprintf("%d", 16+jobIndex),
		},
	}

	if command == "sync" {
		dimensions.Options.FlagsSet = []string{"compare-hash", "delete-destination", "recursive"}
		dimensions.Options.Values = map[string]string{
			"OptCompareHash":       "MD5",
			"OptDeleteDestination": "false",
			"OptRecursive":         "true",
		}
	}

	return dimensions
}

func randomInt64(random *rand.Rand, minimum, maximum int64) int64 {
	return minimum + random.Int63n(maximum-minimum+1)
}

func randomFloat64(random *rand.Rand, minimum, maximum float64) float64 {
	return minimum + random.Float64()*(maximum-minimum)
}

func sampleFinishedEvent(random *rand.Rand, resource aztelemetry.ResourceAttributes, dimensions aztelemetry.JobDimensions, runID, invocationID string, start time.Time, duration time.Duration, jobIndex int) aztelemetry.JobFinishedEvent {
	bytesEnumerated := randomInt64(random, 250_000_000, 25_000_000_000)
	bytesExpected := bytesEnumerated
	bytesTransferred := bytesEnumerated
	objectsScheduled := randomInt64(random, 300, 6_000)
	objectsCompleted := objectsScheduled
	percentComplete := 100.0
	jobStatus := "Completed"
	terminalStage := "completed"
	jobErrorCategory := ""
	jobErrorCode := ""
	failureErrorCodes := ""
	failureErrorOtherCount := int64(0)
	objectsFailed := int64(0)

	switch jobIndex {
	case 1:
		jobStatus = "CompletedWithErrors"
		jobErrorCategory = "transfer"
		jobErrorCode = "transfer-failures"
		failureErrorCodes = fmt.Sprintf("403:%d,503:%d", randomInt64(random, 1, 8), randomInt64(random, 1, 4))
		failureErrorOtherCount = randomInt64(random, 1, 5)
		objectsFailed = randomInt64(random, 1, objectsScheduled/20+1)
		objectsCompleted -= objectsFailed
	case 2:
		jobStatus = "Failed"
		terminalStage = "transfer"
		jobErrorCategory = "network"
		jobErrorCode = "network-error"
		failureErrorCodes = fmt.Sprintf("500:%d", randomInt64(random, 2, 12))
		failureErrorOtherCount = randomInt64(random, 1, 6)
		percentComplete = randomFloat64(random, 25, 85)
		objectsCompleted = int64(float64(objectsScheduled) * percentComplete / 100)
		objectsFailed = randomInt64(random, 1, (objectsScheduled-objectsCompleted)/4+1)
	case 3:
		jobStatus = "Cancelled"
		terminalStage = "transfer"
		percentComplete = randomFloat64(random, 15, 75)
		objectsCompleted = int64(float64(objectsScheduled) * percentComplete / 100)
	case 4:
		jobStatus = "CompletedWithSkipped"
		objectsCompleted -= randomInt64(random, 1, objectsScheduled/15+1)
	}

	objectsSkipped := objectsScheduled - objectsCompleted - objectsFailed
	if objectsCompleted < objectsScheduled {
		bytesTransferred = int64(float64(bytesEnumerated) * float64(objectsCompleted) / float64(objectsScheduled))
		bytesExpected = bytesTransferred
	}
	retryBytes := int64(float64(bytesTransferred) * randomFloat64(random, 0.01, 0.15))
	incompleteBytes := bytesEnumerated - bytesTransferred
	incompleteTrafficBytes := int64(float64(incompleteBytes) * randomFloat64(random, 0.05, 0.35))
	bytesOverWire := bytesTransferred + retryBytes + incompleteTrafficBytes

	jobSeconds := duration.Seconds()
	transferSeconds := jobSeconds * randomFloat64(random, 0.55, 0.95)
	throughput := float64(bytesTransferred) * 8 / 1_000_000 / jobSeconds
	transferThroughput := float64(bytesTransferred) * 8 / 1_000_000 / transferSeconds
	symlinksScheduled := randomInt64(random, 0, 30)
	hardlinksScheduled := randomInt64(random, 0, 20)
	folderPropertiesScheduled := randomInt64(random, 15, 200)
	folderPropertiesFailed := int64(0)
	if jobStatus == "CompletedWithErrors" || jobStatus == "Failed" {
		folderPropertiesFailed = randomInt64(random, 1, 4)
	}
	folderPropertiesSkipped := int64(0)
	if jobStatus == "Cancelled" {
		folderPropertiesSkipped = folderPropertiesScheduled - int64(float64(folderPropertiesScheduled)*percentComplete/100) - folderPropertiesFailed
	} else if jobStatus == "CompletedWithSkipped" {
		folderPropertiesSkipped = randomInt64(random, 1, folderPropertiesScheduled/5+1)
	}
	folderPropertiesCompleted := folderPropertiesScheduled - folderPropertiesFailed - folderPropertiesSkipped
	sourceObjectsScanned := objectsScheduled + randomInt64(random, 20, 1_000)
	sourceBytesScanned := bytesEnumerated + int64(float64(bytesEnumerated)*randomFloat64(random, 0.01, 0.35))
	sourceObjectSizeP50 := randomInt64(random, 64*1024, 4*1024*1024)
	sourceObjectSizeP90 := sourceObjectSizeP50 * randomInt64(random, 2, 12)
	sourceObjectSizeP95 := sourceObjectSizeP90 * randomInt64(random, 1, 4)
	sourceObjectsUnder1MiB := int64(float64(sourceObjectsScanned) * randomFloat64(random, 0.1, 0.85))
	containersScanned := int64(0)
	containersTouched := int64(0)
	bucketsScanned := int64(0)
	bucketsTouched := int64(0)
	switch dimensions.SourceType {
	case "Blob", "BlobFS", "File":
		containersScanned = 1
		containersTouched = 1
		if dimensions.SourceScope == "service" {
			containersScanned = randomInt64(random, 2, 8)
			containersTouched = randomInt64(random, 1, containersScanned)
		}
	case "S3", "GCP":
		bucketsScanned = 1
		bucketsTouched = 1
	}
	storageHTTPAttemptCount := objectsScheduled*randomInt64(random, 1, 4) + randomInt64(random, 20, 500)
	networkErrorAttemptCount := randomInt64(random, 0, storageHTTPAttemptCount/50+1)
	serverBusyThroughputCount := randomInt64(random, 0, storageHTTPAttemptCount/100+1)
	serverBusyIOPSCount := randomInt64(random, 0, storageHTTPAttemptCount/120+1)
	serverBusyOtherCount := randomInt64(random, 0, storageHTTPAttemptCount/150+1)
	serverBusy503Count := serverBusyThroughputCount + serverBusyIOPSCount + serverBusyOtherCount
	performanceConstraints := []string{"Service", "Network", "Disk", "CPU"}
	performanceAdvice := []string{"NetworkErrors", "IncreaseConcurrency", "CheckDiskThroughput", "ReduceCPUContention"}
	performanceIndex := random.Intn(len(performanceConstraints))

	return aztelemetry.JobFinishedEvent{
		Resource:                        resource,
		Dimensions:                      dimensions,
		JobID:                           runID,
		InvocationID:                    invocationID,
		StartTimestamp:                  start,
		EndTimestamp:                    start.Add(duration),
		FinishedCount:                   1,
		JobStatus:                       jobStatus,
		TerminalStage:                   terminalStage,
		JobErrorCategory:                jobErrorCategory,
		JobErrorCode:                    jobErrorCode,
		FailureErrorCodes:               failureErrorCodes,
		FailureErrorOtherCount:          failureErrorOtherCount,
		PerformanceConstraint:           performanceConstraints[performanceIndex],
		PerformanceAdviceCodes:          []string{performanceAdvice[performanceIndex], "ConcurrencyHitUpperLimit"},
		BytesEnumerated:                 bytesEnumerated,
		BytesExpected:                   bytesExpected,
		BytesTransferred:                bytesTransferred,
		BytesOverWire:                   bytesOverWire,
		ObjectsScheduled:                objectsScheduled,
		RegularFilesScheduled:           objectsScheduled - symlinksScheduled - hardlinksScheduled,
		SymlinksScheduled:               symlinksScheduled,
		HardlinksConvertedScheduled:     hardlinksScheduled,
		FolderPropertiesScheduled:       folderPropertiesScheduled,
		ObjectsCompleted:                objectsCompleted,
		ObjectsFailed:                   objectsFailed,
		ObjectsSkipped:                  objectsSkipped,
		FolderPropertiesCompleted:       folderPropertiesCompleted,
		FolderPropertiesFailed:          folderPropertiesFailed,
		FolderPropertiesSkipped:         folderPropertiesSkipped,
		SourceObjectsScanned:            sourceObjectsScanned,
		SourceBytesScanned:              sourceBytesScanned,
		SourceAverageObjectSizeBytes:    float64(sourceBytesScanned) / float64(sourceObjectsScanned),
		SourceObjectSizeP50BytesApprox:  sourceObjectSizeP50,
		SourceObjectSizeP90BytesApprox:  sourceObjectSizeP90,
		SourceObjectSizeP95BytesApprox:  sourceObjectSizeP95,
		SourceObjectsUnder1MiB:          sourceObjectsUnder1MiB,
		SourceObjectsUnder1MiBRatioPct:  100 * float64(sourceObjectsUnder1MiB) / float64(sourceObjectsScanned),
		SourceMaxDirectoryDepth:         randomInt64(random, 2, 24),
		ContainersScanned:               containersScanned,
		ContainersTouched:               containersTouched,
		BucketsScanned:                  bucketsScanned,
		BucketsTouched:                  bucketsTouched,
		TransfersCompleted:              objectsCompleted + folderPropertiesCompleted,
		TransfersFailed:                 objectsFailed + folderPropertiesFailed,
		TransfersSkipped:                objectsSkipped + folderPropertiesSkipped,
		TransfersTotal:                  objectsScheduled + folderPropertiesScheduled,
		JobDurationSeconds:              jobSeconds,
		EnumerationPhaseDurationSeconds: jobSeconds * randomFloat64(random, 0.15, 0.75),
		TransferPhaseDurationSeconds:    transferSeconds,
		JobThroughputMbps:               throughput,
		TransferPhaseThroughputMbps:     transferThroughput,
		AverageStorageHTTPAttemptE2EMs:  randomInt64(random, 20, 400),
		AvgIOPS:                         randomInt64(random, 100, 5_000),
		StorageHTTPAttemptCount:         storageHTTPAttemptCount,
		NetworkErrorAttemptCount:        networkErrorAttemptCount,
		ServerBusy503Count:              serverBusy503Count,
		ServerBusyThroughputCount:       serverBusyThroughputCount,
		ServerBusyIOPSCount:             serverBusyIOPSCount,
		ServerBusyOtherCount:            serverBusyOtherCount,
		ServerBusyPct:                   100 * float64(serverBusy503Count) / float64(storageHTTPAttemptCount),
		NetworkErrorPct:                 100 * float64(networkErrorAttemptCount) / float64(storageHTTPAttemptCount),
		PercentComplete:                 percentComplete,
	}
}

func printEventSummary(events []aztelemetry.MetricEvent) {
	counts := make(map[string]int)
	for _, event := range events {
		counts[event.EventName()]++
	}
	fmt.Printf("dry run: %d events, no telemetry sent\n", len(events))
	fmt.Printf("  azcopy.command.invoked: %d\n", counts["azcopy.command.invoked"])
	fmt.Printf("  azcopy.job.started: %d\n", counts["azcopy.job.started"])
	fmt.Printf("  azcopy.job.finished: %d\n", counts["azcopy.job.finished"])
}
