// Visual: Time chart
// Received telemetry values.
customEvents
| where name startswith 'azcopy.'
| mv-expand MetricName = bag_keys(customMeasurements)
| extend name = tostring(MetricName)
| extend value = todouble(customMeasurements[name])
| project-away MetricName
| where timestamp between (_startTime .. _endTime)
| where name in ('azcopy.command.invoked', 'azcopy.job.started', 'azcopy.job.finished')
| summarize Value = sum(value) by bin(timestamp, 1h), Metric = name
| order by timestamp asc