// Visual: Time chart
customEvents
| where name startswith 'azcopy.'
| mv-expand MetricName = bag_keys(customMeasurements)
| extend name = tostring(MetricName)
| extend value = todouble(customMeasurements[name])
| project-away MetricName
| where timestamp between (_startTime .. _endTime)
| where name in (
    'azcopy.objects_completed',
    'azcopy.objects_failed',
    'azcopy.objects_skipped',
    'azcopy.folder_properties_completed',
    'azcopy.folder_properties_failed',
    'azcopy.folder_properties_skipped')
| summarize Objects = sum(value) by bin(timestamp, 1h), Metric = name
| order by timestamp asc