// Visual: Time chart
customEvents
| where name startswith 'azcopy.'
| mv-expand MetricName = bag_keys(customMeasurements)
| extend name = tostring(MetricName)
| extend value = todouble(customMeasurements[name])
| project-away MetricName
| where timestamp between (_startTime .. _endTime)
| where name in ('azcopy.transfers_completed', 'azcopy.transfers_failed', 'azcopy.transfers_skipped', 'azcopy.transfers_total')
| summarize Transfers = sum(value) by bin(timestamp, 1h), Metric = name
| order by timestamp asc