// Visual: Table
customEvents
| where name startswith 'azcopy.'
| mv-expand MetricName = bag_keys(customMeasurements)
| extend name = tostring(MetricName)
| extend value = todouble(customMeasurements[name])
| project-away MetricName
| where timestamp between (_startTime .. _endTime)
| where name in ('azcopy.average_storage_http_attempt_e2e_ms', 'azcopy.avg_iops')
| summarize SampleSize = count(), Average = avg(value), P50 = percentile(value, 50), P95 = percentile(value, 95), Maximum = max(value) by Metric = name
| project Metric, SampleSize, Average = round(Average, 2), P50 = round(P50, 2), P95 = round(P95, 2), Maximum
| order by Metric asc