// Visual: Time chart
customEvents
| where name startswith 'azcopy.'
| mv-expand MetricName = bag_keys(customMeasurements)
| extend name = tostring(MetricName)
| extend value = todouble(customMeasurements[name])
| project-away MetricName
| where timestamp between (_startTime .. _endTime)
| where name in ('azcopy.server_busy_pct', 'azcopy.network_error_pct', 'azcopy.percent_complete')
| summarize AveragePct = avg(value) by bin(timestamp, 1h), Metric = name
| order by timestamp asc