// Visual: Column chart
customEvents
| where name startswith 'azcopy.'
| where timestamp between (_startTime .. _endTime)
| where name == 'azcopy.job.finished'
| extend Value = tostring(coalesce(customDimensions.AzCopyVersion, customDimensions.ServiceVersion))
| extend Value = iif(isempty(Value), 'unknown', Value)
| summarize Attempts = count() by Value
| top 20 by Attempts desc
| order by Attempts desc