parameters:
  - name: job_name
    type: string
  - name: custom_pool
    type: boolean
    default: false
  - name: test_cli_param
    type: string

jobs:
  - job: ${{ parameters.job_name }}
    timeoutInMinutes: 360
    ${{ if eq(parameters.custom_pool, false) }}:
      strategy:
        matrix:
          Linux:
            imageName: 'ubuntu-latest'
            GOOS: 'linux'
            GOARCH: 'amd64'
            build_name: 'azcopy_linux_amd64'
            display_name: 'Linux'
            type: 'linux'
          Linux-FIPS-disabled:
            imageName: 'ubuntu-latest'
            GOOS: 'linux'
            GOARCH: 'amd64'
            build_name: 'azcopy_linux_fips_amd64'
            display_name: 'Linux-FIPS-disabled'
            type: 'linux-fips'
            fips: 'disabled'
          Windows:
            imageName: 'windows-latest'
            GOOS: 'windows'
            GOARCH: 'amd64'
            build_name: 'azcopy_windows_amd64.exe'
            display_name: 'Windows'
            type: 'windows'
          MacOS:
            imageName: 'macos-latest'
            GOOS: 'darwin'
            GOARCH: 'amd64'
            build_name: 'azcopy_darwin_amd64'
            display_name: 'MacOS'
            type: 'mac-os'
      pool:
        vmImage: $(imageName)
    ${{ else }}:
      strategy:
        matrix:
          Linux-FIPS-enabled:
            # Azure Linux 3.0 enables FIPS by default.
            imageName: 'azurelinux3'
            GOOS: 'linux'
            GOARCH: 'amd64'
            build_name: 'azcopy_linux_fips_amd64'
            display_name: 'Linux-FIPS-enabled'
            type: 'linux-fips'
            fips: 'enabled'
      pool:
        name: 'azcopy-pool'
        demands:
          - ImageOverride -equals $(imageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'Install-Module -Name Az.Accounts -Scope CurrentUser -Repository PSGallery -AllowClobber -Force'
          pwsh: 'true'
        displayName: 'Install Powershell Az Module'

      - task: GoTool@0
        inputs:
          version: $(AZCOPY_GOLANG_VERSION_COVERAGE)
          # We use the Microsoft build of Go to produce FIPS-capable Linux builds.
          goDownloadUrl: 'https://aka.ms/golang/release/latest'
        displayName: 'Install Microsoft build of Go'
        # Don't run if job is canceled
        condition: and(succeededOrFailed(), eq(variables.type, 'linux-fips'))

      - task: GoTool@0
        inputs:
          version: $(AZCOPY_GOLANG_VERSION_COVERAGE)
        displayName: 'Install Go'
        # Don't run if job is canceled
        condition: and(succeededOrFailed(), ne(variables.type, 'linux-fips'))

      - script: |
          go install github.com/jstemmer/go-junit-report@v0.9.1
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.0.0
          go install github.com/matm/gocov-html@v0.0.0-20200509184451-71874e2e203b
        displayName: 'Install dependencies'

      - bash: |
          # Include the job name in the report names, to distinguish the old and new E2E test sets that are both run using this same template.
          baseReportName="${{ parameters.job_name }}_$(display_name)"
          echo "##vso[task.setvariable variable=junitReportName]${baseReportName}_report.xml"
          echo "##vso[task.setvariable variable=baseCoverageReportName]${baseReportName}_coverage"
        displayName: 'Set Report Names'
        # Later steps that run on failure use variables set in this step.
        condition: succeededOrFailed()

      - bash: |
          npm install -g azurite
          mkdir azurite
          azurite --silent --location azurite --skipApiVersionCheck --debug azurite\debug.log &
        displayName: 'Install and Run Azurite'

      - task: AzureCLI@2
        inputs:
          azureSubscription: azcopytestworkloadidentity
          addSpnToEnvironment: true
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            # Create coverage directory
            if (-Not (Test-Path -Path "./coverage")) {
              New-Item -Path "./coverage" -ItemType Directory
            }
            
            # Create log directory
            if (-Not (Test-Path -Path "${env:AZCOPY_E2E_LOG_OUTPUT}")) {
              New-Item -Path "${env:AZCOPY_E2E_LOG_OUTPUT}" -ItemType Directory
            }
            
            # Set platform-specific variables
            $tags = ""
            $suffix = ""
            if ($IsWindows) {
              $suffix = ".exe"
              $env:CGO_ENABLED = "0"
            } elseif ($IsLinux) {
              $tags = "netgo"
              if ("$(type)" -eq "linux-fips") {
                # CGO_ENABLED should always be set to 1 when testing the FIPS build, even when testing with FIPS disabled,
                # to ensure we test the crypto backend that decides at runtime whether to use a FIPS-compliant implementation or not.
                $env:CGO_ENABLED = "1"
                if ("$(fips)" -eq "enabled") {
                  $env:GOFIPS = "1"
                } elseif ("$(fips)" -eq "disabled") {
                  # WARNING: GOFIPS=0 won't disable FIPS in version 1.27+ of the Microsoft build of Go.
                  # See https://github.com/microsoft/go/blob/microsoft/main/eng/doc/fips/README.md#usage-runtime
                  $env:GOFIPS = "0"
                }
              }
            } elseif ($IsMacOS) {
              $env:CGO_ENABLED = "1"
            } else {
              Write-Error "Unsupported operating system"
              exit 1
            }
            
            # Build the Go program
            Write-Output "Building executable"
            if ($tags -ne "") {
              go build -cover -tags $tags -o "$(build_name)"
            } else {
              go build -cover -o "$(build_name)"
            }
            
            # Az PS login
            Connect-AzAccount -FederatedToken $env:idToken -Tenant $env:tenantId -ApplicationId $env:servicePrincipalId
            $null = Get-AzAccessToken -AsSecureString

            # Generate the name of the file the test results will be written to
            $testResultsFileName = "test.txt"
            
            # Run tests and pipe output to a file
            Write-Output "Running tests. Writing results to ${testResultsFileName}."
            go test -timeout=2h -v ${{ parameters.test_cli_param }} ./e2etest | Tee-Object -FilePath "$testResultsFileName"
            
            # Save the exit code from the previous command
            $exitCode = $LASTEXITCODE
            
            # Print the test results from the file
            # Get-Content "$testResultsFileName"
            
            # Generate the jUnit report
            Write-Output "Generating jUnit report $(junitReportName)"
            Get-Content "$testResultsFileName" | & "$(go env GOPATH)/bin/go-junit-report" > "$(junitReportName)"
            
            # Convert coverage data to text format
            Write-Output "Converting coverage data to legacy text format as $(baseCoverageReportName).txt"
            go tool covdata textfmt -i=coverage -o "$(baseCoverageReportName).txt"
            
            # Convert coverage data to JSON format
            Write-Output "Converting coverage data to JSON format as $(baseCoverageReportName).json"
            & "$(go env GOPATH)/bin/gocov$suffix" convert "$(baseCoverageReportName).txt" > "$(baseCoverageReportName).json"
            
            # Convert coverage data to XML format
            Write-Output "Converting coverage data to XML format as $(baseCoverageReportName).xml"
            Get-Content "$(baseCoverageReportName).json" | & "$(go env GOPATH)/bin/gocov-xml$suffix" > "$(baseCoverageReportName).xml"
            
            # Return the exit code from above
            exit $exitCode
        env:
          GOOS: '$(GOOS)'
          GOARCH: '$(GOARCH)'
          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
          AZCOPY_E2E_CLASSIC_ACCOUNT_NAME: $(AZCOPY_E2E_CLASSIC_ACCOUNT_NAME)
          AZCOPY_E2E_CLASSIC_ACCOUNT_KEY: $(AZCOPY_E2E_CLASSIC_ACCOUNT_KEY)
          AZCOPY_E2E_LOG_OUTPUT: '$(System.DefaultWorkingDirectory)/logs'
          AZCOPY_E2E_OAUTH_MANAGED_DISK_CONFIG: $(AZCOPY_E2E_OAUTH_MANAGED_DISK_CONFIG)
          AZCOPY_E2E_OAUTH_MANAGED_DISK_SNAPSHOT_CONFIG: $(AZCOPY_E2E_OAUTH_MANAGED_DISK_SNAPSHOT_CONFIG)
          AZCOPY_E2E_STD_MANAGED_DISK_CONFIG: $(AZCOPY_E2E_STD_MANAGED_DISK_CONFIG)
          AZCOPY_E2E_STD_MANAGED_DISK_SNAPSHOT_CONFIG: $(AZCOPY_E2E_STD_MANAGED_DISK_SNAPSHOT_CONFIG)
          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
          AZCOPY_E2E_EXECUTABLE_PATH: $(System.DefaultWorkingDirectory)/$(build_name)
          GOCOVERDIR: '$(System.DefaultWorkingDirectory)/coverage'
          NEW_E2E_SUBSCRIPTION_ID: $(AZCOPY_NEW_E2E_SUBSCRIPTION_ID)
          NEW_E2E_AZCOPY_PATH: $(System.DefaultWorkingDirectory)/$(build_name)
          NEW_E2E_ENVIRONMENT: "AzurePipeline"
          AZCOPY_E2E_PREMIUM_FILESHARE_ACCOUNT_KEY: $(AZCOPY_E2E_PREMIUM_FILESHARE_ACCOUNT_KEY)
          AZCOPY_E2E_PREMIUM_FILESHARE_ACCOUNT_NAME: $(AZCOPY_E2E_PREMIUM_FILESHARE_ACCOUNT_NAME)
        displayName: 'E2E Test $(display_name) - AMD64 with Workload Identity'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish logs'
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)/logs'
          artifactName: logs
        condition: succeededOrFailed()

      - task: PublishTestResults@2
        inputs:
          testRunner: JUnit
          testResultsFiles: '$(System.DefaultWorkingDirectory)/**/$(junitReportName)'
          testRunTitle: '${{ parameters.job_name }}: $(display_name)'
        condition: succeededOrFailed()

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/$(baseCoverageReportName).xml'
          additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/$(baseCoverageReportName).html'
        condition: succeededOrFailed()
