parameters:
  - name: job_name
    type: string
  - name: test_cli_param
    type: string

jobs:
  - job: ${{ parameters.job_name }}
    timeoutInMinutes: 360
    # Creating strategies for GOOS: Windows Server 2019 /macOS X Mojave 10.15/Ubuntu 20.04
    strategy:
      matrix:
        Linux:
          imageName: 'ubuntu-latest'
          GOOS: 'linux'
          GOARCH: 'amd64'
          build_name: 'azcopy_linux_amd64'
          display_name: 'Linux'
          testReportName: 'Linux_report'
          coverageReportName: 'Linux_coverage'
        Windows:
          imageName: 'windows-latest'
          GOOS: 'windows'
          GOARCH: 'amd64'
          build_name: 'azcopy_windows_amd64.exe'
          display_name: 'Windows'
          testReportName: 'Windows_report'
          coverageReportName: 'Windows_coverage'
          type: 'windows'
        MacOS:
          imageName: 'macos-latest'
          GOOS: 'darwin'
          GOARCH: 'amd64'
          build_name: 'azcopy_darwin_amd64'
          display_name: 'MacOS'
          testReportName: 'MacOS_report'
          coverageReportName: 'MacOS_coverage'
    pool:
      vmImage: $(imageName)
    variables:
      coverageDir: 'coverage'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'Install-Module -Name Az.Accounts -Scope CurrentUser -Repository PSGallery -AllowClobber -Force'
          pwsh: 'true'
        displayName: 'Install Powershell Az Module'

      - task: GoTool@0
        inputs:
          version: $(AZCOPY_GOLANG_VERSION_COVERAGE)
        displayName: 'Install Go'

      - script: |
          go install github.com/jstemmer/go-junit-report@v0.9.1
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.0.0
          go install github.com/matm/gocov-html@v0.0.0-20200509184451-71874e2e203b
        displayName: 'Install Code Coverage and Test Report Dependencies'

      - bash: |
          npm install -g azurite
          mkdir azurite
          azurite --silent --location azurite --skipApiVersionCheck --debug azurite\debug.log &
        displayName: 'Install and Run Azurite'

      - task: AzureCLI@2
        inputs:
          azureSubscription: azcopytestworkloadidentity
          addSpnToEnvironment: true
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            # Create coverage directory
            if (-Not (Test-Path -Path "./$(coverageDir)")) {
              New-Item -Path "./$(coverageDir)" -ItemType Directory
            }
            
            # Create log directory
            if (-Not (Test-Path -Path "${env:AZCOPY_E2E_LOG_OUTPUT}")) {
              New-Item -Path "${env:AZCOPY_E2E_LOG_OUTPUT}" -ItemType Directory
            }
            
            # Set platform-specific variables
            $tags = ""
            $suffix = ""
            if ($IsWindows) {
              $suffix = ".exe"
              $env:CGO_ENABLED = "0"
            } elseif ($IsLinux) {
              $tags = "netgo"
            } elseif ($IsMacOS) {
              $env:CGO_ENABLED = "1"
            } else {
              Write-Error "Unsupported operating system"
              exit 1
            }
            
            # Build the Go program
            Write-Output "Building executable"
            if ($tags -ne "") {
              go build -cover -tags $tags -o "$(build_name)"
            } else {
              go build -cover -o "$(build_name)"
            }
            
            # Az PS login
            Connect-AzAccount -FederatedToken $env:idToken -Tenant $env:tenantId -ApplicationId $env:servicePrincipalId
            $null = Get-AzAccessToken -AsSecureString
            
            # Run tests, write coverage data to a directory, and pipe output to a file
            Write-Output "Running tests. Writing coverage data to `"$(coverageDir)`" directory and test results to $(testReportName).txt."
            go test -timeout=2h -v ${{ parameters.test_cli_param }} ./e2etest | Tee-Object -FilePath "$(testReportName).txt"
            
            # Save the exit code from the previous command
            $exitCode = $LASTEXITCODE
            
            # Print the test results from the file
            # Get-Content "$(testReportName).txt"

            # Generate the jUnit report
            Write-Output "Generating jUnit report $(testReportName).xml"
            Get-Content "$(testReportName).txt" | & "$(go env GOPATH)/bin/go-junit-report" > "$(testReportName).xml"
            
            # Convert coverage data to text format
            Write-Output "Generating plain-text coverage report $(coverageReportName).txt"
            go tool covdata textfmt -i="$(coverageDir)" -o "$(coverageReportName).txt"
            
            # Convert coverage data to JSON format
            Write-Output "Generating JSON coverage report $(coverageReportName).json"
            & "$(go env GOPATH)/bin/gocov$suffix" convert "$(coverageReportName).txt" > "$(coverageReportName).json"
            
            # Convert coverage data to XML format
            Write-Output "Generating XML coverage report $(coverageReportName).xml"
            Get-Content "$(coverageReportName).json" | & "$(go env GOPATH)/bin/gocov-xml$suffix" > "$(coverageReportName).xml"
            
            # Return the exit code from above
            exit $exitCode
        env:
          GOOS: '$(GOOS)'
          GOARCH: '$(GOARCH)'
          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
          AZCOPY_E2E_CLASSIC_ACCOUNT_NAME: $(AZCOPY_E2E_CLASSIC_ACCOUNT_NAME)
          AZCOPY_E2E_CLASSIC_ACCOUNT_KEY: $(AZCOPY_E2E_CLASSIC_ACCOUNT_KEY)
          AZCOPY_E2E_LOG_OUTPUT: '$(System.DefaultWorkingDirectory)/logs'
          AZCOPY_E2E_OAUTH_MANAGED_DISK_CONFIG: $(AZCOPY_E2E_OAUTH_MANAGED_DISK_CONFIG)
          AZCOPY_E2E_OAUTH_MANAGED_DISK_SNAPSHOT_CONFIG: $(AZCOPY_E2E_OAUTH_MANAGED_DISK_SNAPSHOT_CONFIG)
          AZCOPY_E2E_STD_MANAGED_DISK_CONFIG: $(AZCOPY_E2E_STD_MANAGED_DISK_CONFIG)
          AZCOPY_E2E_STD_MANAGED_DISK_SNAPSHOT_CONFIG: $(AZCOPY_E2E_STD_MANAGED_DISK_SNAPSHOT_CONFIG)
          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
          AZCOPY_E2E_EXECUTABLE_PATH: $(System.DefaultWorkingDirectory)/$(build_name)
          GOCOVERDIR: '$(System.DefaultWorkingDirectory)/$(coverageDir)'
          NEW_E2E_SUBSCRIPTION_ID: $(AZCOPY_NEW_E2E_SUBSCRIPTION_ID)
          NEW_E2E_AZCOPY_PATH: $(System.DefaultWorkingDirectory)/$(build_name)
          NEW_E2E_ENVIRONMENT: "AzurePipeline"
        displayName: 'Run Tests with Workload Identity'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)/logs'
          artifactName: logs
        displayName: 'Publish logs'
        condition: succeededOrFailed()

      - task: PublishTestResults@2
        inputs:
          testRunner: JUnit
          testResultsFiles: '$(System.DefaultWorkingDirectory)/**/$(testReportName).xml'
          testRunTitle: '${{ parameters.job_name }}: $(display_name)'
        condition: succeededOrFailed()

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/$(coverageReportName).xml'
          additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/$(coverageReportName).html'
        condition: succeededOrFailed()
