jobs:
  - job: Unit_and_Python_Tests
    variables:
      isMutexSet: 'false'
      nonFederatedUnitTestDirectories: 'azcopy, cmd, common, common/parallel, jobsAdmin, mock_server, sddl, traverser'
      federatedUnitTestDirectories: 'ste'
      pythonCoverageDirectory: 'coverage'
      pythonCoverageReportName: 'smoke_coverage'
    # allow maximum build time, in case we have build congestion
    timeoutInMinutes: 360
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
        displayName: 'Install Python'

      - task: GoTool@0
        inputs:
          version: $(AZCOPY_GOLANG_VERSION_COVERAGE)
        displayName: 'Install Go'

      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'ci-gcs-dev.json'
        name: ciGCSServiceAccountKey
        displayName: 'Download GCS Service Account Key'

      - bash: |
          go install github.com/jstemmer/go-junit-report/v2@v2.1.0
          go install github.com/axw/gocov/gocov@v1.1.0 # this version is required by gocov-xml@v1.2.0
          go install github.com/AlekSi/gocov-xml@v1.2.0
        displayName: 'Install Code Coverage and Test Report Dependencies'

      - script: |
          pip install azure-storage-blob==12.12.0
          pip install azure-storage-blob six
          # set the variable to indicate that the mutex is being acquired
          # note: we set it before acquiring the mutex to ensure we release the mutex. 
          # setting this after can result in an un-broken mutex if someone cancels the pipeline after we acquire the 
          # mutex but before we set this variable.
          # setting this before will always work since it is valid to break an un-acquired mutex.
          echo '##vso[task.setvariable variable=isMutexSet]true'
          # acquire the mutex before running live tests to avoid conflicts
          python ./tool_distributed_mutex.py lock "$(MUTEX_URL)"
        displayName: 'Acquire the Distributed Mutex'

      - ${{ each directory in split(variables.nonFederatedUnitTestDirectories, ', ') }}:
        # We use the directory to generate report names that are inserted into filepaths in multiple tasks below,
        # so we replace all forward slashes in `directory` with periods, to avoid creating directories when inserting it into the paths.
        # It's a bit of a hack, but we use `each` to perform this replacement only once and store the result in a variable all tasks can reference;
        # that requires putting the variable in an array, which is why we then use `split` with a delimiter we know won't split the string.
        - ${{ each coverage_name in split(replace(directory, '/', '.'), '/') }}:
          - task: ShellScript@2
            inputs:
              scriptPath: './azurePipelineTemplates/run_ut.sh'
              disableAutoCwd: true
              cwd: '$(System.DefaultWorkingDirectory)'
            env:
              directory: ${{ directory }}
              testReportName: '${{ coverage_name }}_report'
              coverageReportName: '${{ coverage_name }}_coverage'
              ACCOUNT_NAME: $(ACCOUNT_NAME)
              ACCOUNT_KEY: $(ACCOUNT_KEY)
              AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
              AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              GOOGLE_APPLICATION_CREDENTIALS: $(ciGCSServiceAccountKey.secureFilePath)
              GOOGLE_CLOUD_PROJECT: $(GOOGLE_CLOUD_PROJECT)
              # All env variables above this comment should be the same for federated and non-federated unit tests.
              AZCOPY_E2E_APPLICATION_ID: $(ACTIVE_DIRECTORY_APPLICATION_ID)
              AZCOPY_E2E_CLIENT_SECRET: $(AZCOPY_SPA_CLIENT_SECRET)
              AZCOPY_E2E_TENANT_ID: $(OAUTH_TENANT_ID)
            displayName: 'Run ${{ directory }} Tests'
            # Don't let a test failure for a different directory prevent this directory from being tested,
            # but don't run if job is canceled or mutex wasn't acquired
            condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))
            
          - task: PublishTestResults@2
            inputs:
              testRunner: JUnit
              testResultsFiles: '$(System.DefaultWorkingDirectory)/**/${{ coverage_name }}_report.xml'
              testRunTitle: '${{ directory }} Tests'
            # Don't run if job is canceled or mutex wasn't acquired (in which case, test task didn't run, so no test results to report)
            condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))

          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/${{ coverage_name }}_coverage.xml'
            # Don't run if job is canceled or mutex wasn't acquired (in which case, test task didn't run, so no test coverage data to report)
            condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))

      - ${{ each directory in split(variables.federatedUnitTestDirectories, ', ') }}:
        # We use the directory to generate report names that are inserted into filepaths in multiple tasks below,
        # so we replace all forward slashes in `directory` with periods, to avoid creating directories when inserting it into the paths.
        # It's a bit of a hack, but we use `each` to perform this replacement only once and store the result in a variable all tasks can reference;
        # that requires putting the variable in an array, which is why we then use `split` with a delimiter we know won't split the string.
        - ${{ each coverage_name in split(replace(directory, '/', '.'), '/') }}:
          - task: AzureCLI@2
            inputs:
              azureSubscription: azcopytestworkloadidentity
              addSpnToEnvironment: true
              scriptType: bash
              scriptLocation: 'scriptPath'
              scriptPath: './azurePipelineTemplates/run_ut.sh'
            env:
              directory: ${{ directory }}
              testReportName: '${{ coverage_name }}_report'
              coverageReportName: '${{ coverage_name }}_coverage'
              ACCOUNT_NAME: $(ACCOUNT_NAME)
              ACCOUNT_KEY: $(ACCOUNT_KEY)
              AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
              AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              GOOGLE_APPLICATION_CREDENTIALS: $(ciGCSServiceAccountKey.secureFilePath)
              GOOGLE_CLOUD_PROJECT: $(GOOGLE_CLOUD_PROJECT)
              # All env variables above this comment should be the same for federated and non-federated unit tests.
              NEW_E2E_ENVIRONMENT: "AzurePipeline"
            displayName: 'Run ${{ directory }} Tests with Workload Identity'
            # Don't let a test failure for a different directory prevent this directory from being tested,
            # but don't run if job is canceled or mutex wasn't acquired
            condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))
            
          - task: PublishTestResults@2
            inputs:
              testRunner: JUnit
              testResultsFiles: '$(System.DefaultWorkingDirectory)/**/${{ coverage_name }}_report.xml'
              testRunTitle: '${{ directory }} Tests'
            # Don't run if job is canceled or mutex wasn't acquired (in which case, test task didn't run, so no test results to report)
            condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))

          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/${{ coverage_name }}_coverage.xml'
            # Don't run if job is canceled or mutex wasn't acquired (in which case, test task didn't run, so no test coverage data to report)
            condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))

      - script: |
          GOARCH=amd64 GOOS=linux go build -cover -tags "netgo" -o azcopy_linux_amd64 
          go build -tags "netgo" -o test-validator ./testSuite/
          mkdir test-temp
          mkdir "$(pythonCoverageDirectory)"
          export AZCOPY_EXECUTABLE_PATH=$(pwd)/azcopy_linux_amd64
          export TEST_SUITE_EXECUTABLE_LOCATION=$(pwd)/test-validator
          export TEST_DIRECTORY_PATH=$(pwd)/test-temp

          # Run tests and write coverage data to a directory
          echo "Running tests. Writing coverage data to \"$(pythonCoverageDirectory)\" directory."
          keyctl session test python ./testSuite/scripts/run.py
          
          # Convert coverage data to text format
          echo "Generating plain-text coverage report $(pythonCoverageReportName).txt"
          go tool covdata textfmt -i="$(pythonCoverageDirectory)" -o "$(pythonCoverageReportName).txt"

          # Convert coverage data to JSON format
          echo "Generating JSON coverage report $(pythonCoverageReportName).json"
          $(go env GOPATH)/bin/gocov convert "$(pythonCoverageReportName).txt" > "$(pythonCoverageReportName).json"
          
          # Convert coverage data to XML format
          echo "Generating XML coverage report $(pythonCoverageReportName).xml"
          $(go env GOPATH)/bin/gocov-xml < "$(pythonCoverageReportName).json" > "$(pythonCoverageReportName).xml"
        env:
          ACCOUNT_NAME: $(ACCOUNT_NAME)
          ACCOUNT_KEY: $(ACCOUNT_KEY)
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
          GOOGLE_CLOUD_PROJECT: $(GOOGLE_CLOUD_PROJECT)
          GOOGLE_APPLICATION_CREDENTIALS: $(ciGCSServiceAccountKey.secureFilePath)
          ACTIVE_DIRECTORY_APPLICATION_ID: $(ACTIVE_DIRECTORY_APPLICATION_ID)
          AZCOPY_SPA_CLIENT_SECRET: $(AZCOPY_SPA_CLIENT_SECRET)
          CONTAINER_OAUTH_URL: $(CONTAINER_OAUTH_URL)
          CONTAINER_OAUTH_VALIDATE_SAS_URL: $(CONTAINER_OAUTH_VALIDATE_SAS_URL)
          CONTAINER_SAS_URL: $(CONTAINER_SAS_URL)
          FILESYSTEM_SAS_URL: $(FILESYSTEM_SAS_URL)
          FILESYSTEM_URL: $(FILESYSTEM_URL)
          OAUTH_AAD_ENDPOINT: $(OAUTH_AAD_ENDPOINT)
          OAUTH_TENANT_ID: $(OAUTH_TENANT_ID)
          PREMIUM_CONTAINER_SAS_URL: $(PREMIUM_CONTAINER_SAS_URL)
          S2S_DST_BLOB_ACCOUNT_SAS_URL: $(S2S_DST_BLOB_ACCOUNT_SAS_URL)
          S2S_SRC_BLOB_ACCOUNT_SAS_URL: $(S2S_SRC_BLOB_ACCOUNT_SAS_URL)
          S2S_SRC_FILE_ACCOUNT_SAS_URL: $(S2S_SRC_FILE_ACCOUNT_SAS_URL)
          S2S_SRC_S3_SERVICE_URL: $(S2S_SRC_S3_SERVICE_URL)
          S2S_SRC_GCP_SERVICE_URL: $(S2S_SRC_GCP_SERVICE_URL)
          SHARE_SAS_URL: $(SHARE_SAS_URL)
          GOCOVERDIR: '$(System.DefaultWorkingDirectory)/$(pythonCoverageDirectory)'
        displayName: 'Run Python Tests'
        # Don't let a unit-test failure prevent the Python tests from running,
        # but don't run if job is canceled or mutex wasn't acquired
        condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))

      # Smoke Tests Publishing
      - task: PublishCodeCoverageResults@2
        inputs:
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/$(pythonCoverageReportName).xml'
        # Don't run if job is canceled or mutex wasn't acquired (in which case, test task didn't run, so no test results to report)
        condition: and(succeededOrFailed(), eq(variables['isMutexSet'], 'true'))

      - script: |
          pip install azure-storage-blob==12.12.0
          python ./tool_distributed_mutex.py unlock "$(MUTEX_URL)"
        displayName: 'Release the Distributed Mutex'
        # If the mutex was acquired by this job, release the mutex - even if the job was canceled
        condition: and(always(), eq(variables['isMutexSet'], 'true'))
