version: "2"
run:
  tests: false
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - e2etest
      - testSuite
    rules:
      - path: e2etest
        linters:
          - staticcheck
        text: "S1008:"
      - path: azbfs/zz_generated_*
        linters:
          - staticcheck
        text: "S1008:"