// Visual: Stacked column chart
// X column: timestamp; Y: Invocations; Series: Command
customEvents
| where name startswith 'azcopy.'
| where timestamp between (_startTime .. _endTime)
| where tostring(customDimensions.SchemaVersion) in ('1', '2', '3')
| where name in ('azcopy.job.finished', 'azcopy.command.invoked')
| extend
    Command = tostring(customDimensions.Command),
    Version = tostring(coalesce(customDimensions.AzCopyVersion, customDimensions.ServiceVersion))
| summarize Invocations = count() by Week = startofweek(timestamp), Command, Version
| project
    timestamp = Week,
    Command = iif(isempty(Command), 'unknown', Command),
    Version = iif(isempty(Version), 'unknown', Version),
    Invocations
| order by timestamp asc, Invocations desc