parameters:
  - name: jobName
    type: string
  - name: useDemands
    type: boolean
  - name: matrix
    type: object
  - name: ubuntu_tag
    type: string
  - name: mariner_tag
    type: string

jobs:
  - job: ${{ parameters.jobName }}
    timeoutInMinutes: 120
    strategy:
      matrix: ${{ parameters.matrix }}
    pool:
      ${{ if eq(parameters.useDemands, true) }}:
        name: "blobfuse-ubn-arm64-pool"
        demands:
          - ImageOverride -equals ${{ parameters.matrix.agentName }}
      ${{ if eq(parameters.useDemands, false) }}:
        vmImage: ${{ parameters.matrix.vmImage }}
      

    steps:
      - checkout: none
      - script: |
          git clone https://github.com/Azure/azure-storage-azcopy
        displayName: 'Checkout Code'
        workingDirectory: $(root_dir)

      - script: |
          git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
        displayName: 'Checkout branch'
        workingDirectory: $(work_dir)

      - ${{ if eq(parameters.jobName, 'Set_2_Ubuntu_Mariner_ARM64') }}:
        - task: ShellScript@2
          inputs:
            scriptPath: "$(work_dir)/go_installer.sh"
            args: "$(root_dir)/ $(AZCOPY_GOLANG_VERSION)"
          displayName: "Installing Go tools"

      - ${{ if eq(parameters.jobName, 'Set_2_Ubuntu_Mariner_ARM64') }}:
        - script: |
            sudo apt update
            sudo apt --fix-broken install
          displayName: "Install dependencies"

      - script: |
          chmod 777 *.sh
          ./dockerinstall.sh

          # Build and publish Docker containers
          ./buildcontainer.sh Dockerfile ${{ parameters.ubuntu_tag }}
          ./publishcontainer.sh $(AZCOPY_DOCKER_REG_USER) $(AZCOPY_DOCKER_REG_PWD) ${{ parameters.ubuntu_tag }}

          ./buildcontainer.sh DockerfileMariner ${{ parameters.mariner_tag }}
          ./publishcontainer.sh $(AZCOPY_DOCKER_REG_USER) $(AZCOPY_DOCKER_REG_PWD) ${{ parameters.mariner_tag }}
        displayName: "Create docker image and push to the containers registry"
        workingDirectory: $(work_dir)/docker
